platanus/trellorama

- README.md
Se modifico el readme, agreando las instrucciones necesarias para que el projecto corra.
> docs(readme): update readme with the project requirements

- src/App.vue
- src/components/BoardInfo.vue
- src/components/BoardList.vue
- src/components/StackedChart.vue
- src/utils/stackedCardData.js
Se implementó una opción para rellenar las listas con las tarjetas del flujo faltante.
- Se modifico la forma en la que se entregan las listas a mostrar
- Se implemento un checkbox para hacer el relleno retroactivo
- Se implemento una función que realiza el relleno retroactivo
> Fix card flow

- src/components/Board.vue
- src/components/BoardInfo.vue
- src/components/BoardList.vue
Se refactorizaron los componentes de board
- Se movieron todos los requests de BoardInfo a Board
- Se movió el gráfico de BoardInfo a Board
- BoardInfo ahora slo muestra la tabla con la información del board
- Board es ahora el componente "raiz" de un board, que se encarga de hacer los requests a las apis y le entrega la información procesada a los distintos sub-componentes
> refactor(board): refactor board components

- package-lock.json
- package.json
- src/components/Board.vue
Se implemento un filtro para eliminar labels de Trello que el usuario no considera utiles.
- Se incorporo la librería vue-select
- Se implemento el filtro por labels de Trello.
> Label filter

- package-lock.json
- package.json
- src/components/Board.vue
Se implemento el filtro de fechas para el gráfico
- Se implemento la librería vuejs-datepicker
- Se implemento un filtro desde y hasta para las fechas
- el filtro hasta es no inclusive
> feat(date filter): implement date filter

- src/components/Board.vue
- src/components/TeamSpeed.vue
- src/utils/getDate.js
- src/utils/stackedCardData.js
Se implemento la metrica 'Team Speed'
- Se creo el componenete TeamSpeed
- Se movio la funcion getDate a utils/getDate.js
> Team speed

- src/components/Board.vue
- src/components/BoardInfo.vue
- src/components/LeadTime.vue
- src/utils/timeBetweenLists.js
Se creo el componente que muestra la métrica de lead time.
- Se creo el componente LeadTime.vue que muestra la métrica de lead time
- Se creo el archivo timeBetweenLists.js para obtener el tiempo que pasa una tarjeta antes de cambiarse de lista, se dejo la función en este archvo ya que puede ser reutilizada en futuras métricas
> Lead time and List time

- src/components/CumulativeWrapper.vue
Se arreglo bug que no se gráficaban las actividades al recibirlas inicialmente.
> fix(cumulativeWrapper): fix card activity watch

- package-lock.json
- package.json
- src/components/BoardInfo.vue
- src/components/LeadTime.vue
- src/utils/timeBetweenLists.js
Se implemento la medición de desviación estandar para lead time
- Se implemento la desviación estandar para lead time
- se refactorizó código en timeBetweenLists.js para evitar hacer calculos repetitivos
> Lead time standard deviation and mode

- src/components/ProjectionChart.vue
Se arreglo bug en donde la proyección para los días seguía considerando la velocidad semanal.
> fix(ProjectionChart): fix projection for days

- src/components/Board.vue
Se implemento la opción de mostrar solo las tarjetas que tengan un label especifico
> feat(Board): implement filter to see cards with a single label

- src/components/ProjectionChart.vue
Se arregló un bug, donde el tiempo de proyeccion se incrementaba en 1 unidad extra
> Time units projection

- src/utils/speedUtil.js
Se arreglo las forma en la que se estaba calculando la velocidad del equipo
> fix(teamSpeed): fix team speed calculation

- package.json
- src/components/Board.vue
- src/components/ProjectionChart.vue
- src/components/ProjectionWrapper.vue
- src/utils/chartUtils.js
Se agregó una linea punteada en el gráfico de proyección con la cantidad de tarjetas actuales del board.
> Projection cards line

- src/components/Board.vue
- src/components/CumulativeWrapper.vue
Se modifico el filtro por fechas para que este sea global en todo el dashboard. No filtra las tarjetas, solo las actividades.
> feat(global date filter): implment global date filter

- src/App.vue
- src/components/Board.vue
- src/components/BoardList.vue
- src/components/BoardSelector.vue
- src/components/Settings.vue
- src/utils/configurationPersistance.js
Se creo un componente para almacenar los tableros y columnas de trello que un usuario quiere ver
- Se creo el componente BoardSelector.vue que gestiona los tableros y las columnas de cada tablero
- Se creo el componente Settings.vue que gestiona todo lo que se refiere a configuraciones
- Se modifico App.vue para cargar las configuraciones
- Se creo el archivo configurationPersistance para manejar el almacenamiento en localStorage
> Board selector

- .eslintrc.json
> style(): set max line lenght to 120 chars

- src/components/BoardInfo.vue
- src/utils/timeBetweenLists.js
Se arreglaron las funciones que calculan la moda y la desviación estándar de manera que no generen errores al calcularse
> fix(timeBetweenLists.js): fix functions so errors are not generated

- src/components/Board.vue
- src/components/ProjectionWrapper.vue
- src/components/TeamSpeed.vue
- src/utils/speedUtil.js
Se arreglo la forma en la que se calcula la velocidad del equipo, ahora se consideran las fechas de inicio y de fin del filtro por fechas
> fix(team speed): fix team speed calculations by date

- src/components/Board.vue
- src/components/CumulativeWrapper.vue
- src/components/ProjectionWrapper.vue
Se guardan todos los parámetros de un board
- Se guarda la fecha inicial del filtro
- No se guarda la fecha final, ya que esta camba todos los días por la fecha actual
- Se guarda el formato de fecha para los gráficos
- Se guardan los parámetros para el gráfico de proyección
> Save configurations

- babel.config.js
- postcss.config.js
- src/components/Board.vue
- src/components/BoardInfo.vue
- src/components/ProjectionChart.vue
- src/components/ProjectionWrapper.vue
- src/components/TeamSpeed.vue
- src/utils/chartUtils.js
- src/utils/speedUtil.js
- src/utils/timeBetweenLists.js
- src/utils/trelloManager.js
Se limpio el código, tanto en estilo como en funcionalidad
- Se arreglaron todos errores de linter respecto al largo de linea
- Se arreglaron errores en el calculo de métricas de timeBetweenLists.js, donde al realizar ciertos filtros por fechas, algunas tarjetas quedaban `undefined`, generando errores
- Se arreglo un error donde se pasaba la fecha inicio del filtro de manera inconsistente
> Clean code

- src/components/ProjectionWrapper.vue
Se modificó la forma en la que se elige el tiempo de proyección. Antes se elegían unidades, ahora se elige la fecha a proyectar
> feat(projectionDate): implement projection date

- src/components/BoardSelector.vue
Se implemento la opcion de seleciconar las columnas "en desarrollo"
> Select lists in settings

- src/components/BoardSelector.vue
- src/utils/chartUtils.js
Ahora es posible definir un WIP Limit para las listas que fueron seleccionadas
> Configure wip limit

- src/components/BoardSelector.vue
- src/components/BoardWizard.vue
Ahora se permite seleccionar mas de una lista como backlog
> feat(settings): allow multiple backlog lists

- src/assets/style.css
- src/components/Board.vue
- src/components/BoardInfo.vue
- src/components/BoardWizard.vue
- src/components/BugChart.vue
- src/components/LeadTime.vue
- src/components/ProjectionChart.vue
- src/components/ProjectionWrapper.vue
- src/components/TeamSpeed.vue
- src/utils/speedUtil.js
Se modifico el wizard con las siguientes detalles
#Detalles
- Todas las categorías pueden tener multiples listas
- Las listas seleccionadas se deducen de las listas en categorías
- Listas archivadas se movió a la configuración avanzada
- Se agregó la opción de elegir etiquetas de bugs en las opciones avanzadas
- Se agregó la opción de elegir un limite para las WIP lists
> Improve Wizard

- src/components/Board.vue
- src/components/BoardInfo.vue
- src/components/LeadTime.vue
- src/components/LeadTimeChart.vue
- src/utils/chartUtils.js
- src/utils/timeBetweenLists.js
Se implemento un lead time mas detallado, con response time, cycle time y deploy time
> Detailed lead time

- src/components/Board.vue
- src/components/CumulativeChart.vue
- src/components/CumulativeWrapper.vue
- src/components/ProjectionChart.vue
- src/components/ProjectionWrapper.vue
- src/utils/chartUtils.js
- src/utils/stackedCardData.js
Se arreglo el filtro de fecha para el gráfico acumulado
> fix(date filter): fix cumulative chart date filter bug

- package-lock.json
- package.json
- src/main.js
> feat(sentry): implement sentry

- src/components/LeadTimeChart.vue
Se agregó el valor a lead time y time to live
> feat(lead time): add values to lead time and time to live

- src/components/Board.vue
- src/components/Card.vue
- src/components/WIPList.vue
- src/components/WIPLists.vue
Se cambio la fecha por el tiempo en lista de las tarjetas en progreso
> feat(wipLists): display card time in the list

- src/utils/speedUtil.js
Se arreglo un bug donde se estaban duplicando las tarjetas listas para el gráfico de proyeccion
> Fix projection

- package-lock.json
- src/utils/chartUtils.js
Se arreglaron errores generales
- Se arreglo una vulnerabilidad de npm
- Se arreglo un warning del linter
> Fix general errors

- src/components/Board.vue
Se elimino el texto (not inclussive) del filtro de fechas
> fix(date filter): remove (not inlcusive) text

- src/components/LeadTimeChart.vue
Se agrego la unidad al gráfico de lead time
> feat(leadTime): add unit to time

- package-lock.json
- package.json
- src/App.vue
- src/components/Board.vue
- src/components/BoardInfo.vue
- src/components/BoardWizard.vue
- src/components/BugChart.vue
- src/components/BugWrapper.vue
- src/components/Card.vue
- src/components/CumulativeWrapper.vue
- src/components/LandingPage.vue
- src/components/LeadTime.vue
- src/components/LeadTimeChart.vue
- src/components/TeamSpeed.vue
- src/components/WIPLists.vue
- src/main.js
- src/utils/localeText.js
Se implemento locale
Se implemento locale en ingles y español para todas las vistas
> Implement locale

- src/components/Board.vue
- src/components/wipHistogram.vue
- src/components/wipHistogramWrapper.vue
- src/utils/localeText.js
- src/utils/timeBetweenLists.js
Se implementó un histograma de los tiempos en lista para las listas WIP
> Wip list histogram

- src/components/wipHistogram.vue
- src/components/wipHistogramWrapper.vue
- src/utils/localeText.js
Se modificó el histograma de tarjetas para mejorar su usabilidad
- Se le agregó titulos a ambos ejes
- Se calculo el tamaño de los bins usando el método de la raiz
- Se agregó la opción de elegir el tamaño del bin
> Improve histogram

- src/components/Board.vue
- src/components/BoardList.vue
- src/components/DashboardSubOptions.vue
- src/components/PresentDashboard.vue
Se modifico el dashboard "actual" agregandole la funcionalidad de sub dashboards, como el pasado
> feat(present dashboard): reorder present dashboard

- src/components/BacklogBugs.vue
- src/components/Board.vue
- src/components/PresentDashboard.vue
- src/utils/localeText.js
Se cambio el porcentaje de bugs por la cantidad de bugs en el backlog
> feat(backlog bugs): replace bugs perecentage for bugs in backlog

- src/components/Board.vue
- src/components/HistoricalBugs.vue
- src/components/HistoricalBugsWrapper.vue
- src/components/PastDashboard.vue
- src/utils/localeText.js
Se cambiaron las métricas, ahoa se utiliza la cantidad de bugs en backlog, en vez de los bugs en listo
> Historical bugs list

- src/components/LeadTimeChart.vue
- src/utils/localeText.js
Se agregó un tooltip con la explicación de cada item en lead time
> feat(lead time): add tooltip with descriptions

- src/utils/localeText.js
Se cambiaron los textos del tooltip de lead time
> feat(lead time): change lead time tooltip texts

- src/components/WipHistogram.vue
- src/components/WipHistogramWrapper.vue
- src/utils/localeText.js
Pequeñas mejoras al histograma
- Se redondea el ancho del bin
- Se le agregó una leyenda al gráfico
> Histogram improvements

- src/assets/style.css
- src/components/PastDashboard.vue
- src/components/WipHistogram.vue
- src/components/WipHistogramWrapper.vue
- src/utils/timeBetweenLists.js
Se agregó la posibilidad de hacer click sobre el histograma, permitiendo ver las tarjetas de este, ordenadas
> Histogram lists

- src/assets/style.css
- src/components/Board.vue
- src/components/DashboardSubOptions.vue
- src/components/HistoricalLeadTime.vue
- src/components/HistoricalLeadTimeWrapper.vue
- src/components/LeadTimeChart.vue
- src/components/PastDashboard.vue
- src/utils/localeText.js
Se implemento un gráfico con las metricas historicas del lead time
- Se elimino un parametro no usado de lead time
- Se implemento un gráfico de barras agrupado para mostrar el lead time en distintas etapas
> Historical lead time

- src/components/Board.vue
- src/components/HistoricalBugs.vue
- src/components/PastDashboard.vue
Se arreglo un problema, donde la cantidad de bugs historicos podia ser negativa
> fix(historical bugs): fix bugs where there could be negative bugs

- src/components/HistoricalSpeed.vue
- src/components/HistoricalSpeedWrapper.vue
- src/utils/localeText.js
Se agrego un gráfico de barras que muestra la velocidad especifica para cada periodo del gráfico
> feat(historical speed): add bar chart for period speed

- src/components/HistoricalBugs.vue
- src/components/HistoricalSpeedWrapper.vue
> minor bug fixes

- src/assets/styles/card.scss
- src/assets/styles/wipHistogramWrapper.scss
- src/assets/styles/wipLists.scss
- src/components/Board.vue
- src/components/Card.vue
- src/components/PastDashboard.vue
- src/components/PresentDashboard.vue
- src/components/WIPList.vue
- src/components/WIPLists.vue
- src/components/WipHistogramWrapper.vue
Se modificó el componente de tarjetas para que se parezca mas a trello
- AHora estan las labels en la tarjeta
- Muestra los usuarios de la tarjeta
> Card style

- src/components/BoardWizard.vue
- src/components/PresentDashboard.vue
- src/components/objectivePercentage.vue
- src/utils/localeText.js
Se puede ver el porcentaje de objetivos listos
- Se pueden seleccionar labels de objetivos
- Se puede ver el porcentaje de objetivos listos en el dashboard
> Objectives

- src/components/Board.vue
- src/components/BoardList.vue
- src/components/objectivePercentage.vue
- src/store/actions.js
Se arregló un error donde no se consideraban las tarjetas archivadas
> fix(vuex): now it asks for archived cards

- src/components/DashboardOptions.vue
Los nuevos miembros y etiquetas son seleccionados automaticamente
> New labels

- src/assets/styles/card.scss
- src/components/Card.vue
Se agrego un tooltip a etiquetas y miembros, que muestran sus nombres al posar el mouse sobre ellos
> feat(cards): add tooltips

- src/components/HistoricalBugs.vue
Se arreglo la forma en la que se estaban contando los bugs por fecha en las listas de backlog
> fix(historical bugs): fix the way the bugs were counted by date

- src/components/Board.vue
- src/components/CumulativeChart.vue
- src/components/ProjectionChart.vue
- src/utils/chartUtils.js
- src/utils/stackedCardData.js
Se filtran las tarjetas que ya no se encuentran presentes
> Exclude not ready

- src/components/Board.vue
- src/components/FutureDashboard.vue
- src/components/ProjectionChart.vue
- src/components/ProjectionWrapper.vue
- src/components/objectivePercentage.vue
- src/utils/chartUtils.js
Se agregaron labels de objetivos, las cuales se ordenan en el gráfico de proyección y muestran sus tarjetas restantes por prioridad
> Goal projection

- src/components/ProjectionChart.vue
Se arregló un bug donde el gráfico de proyección no proyectaba a futuro
> fix(projection chart): fix projection

- src/components/ProjectionChart.vue
Se arreglo el filtrado de etiquetas en el gráfico de proyección
> fix(projection chart): fix projection label filter

- src/assets/styles/boardWizard.scss
- src/components/BoardWizard.vue
- src/utils/localeText.js
No hay cambios tan significativos, se arreglan problemas como las posiciones de las cajas que se deformaban, así como la posición del botón inferior. Se eliminan algunas clases redundantes o sin uso y se cambian algunos nombres o tags para ser un poco más explicativos. Esto es solo para el componente del Wizard.
> refactor(): clean scss and fix little style problems

- src/assets/styles/backlogBugs.scss
- src/assets/styles/boardList.scss
- src/assets/styles/dashboard.scss
- src/assets/styles/wipList.scss
- src/assets/styles/wipLists.scss
- src/components/BacklogBugs.vue
- src/components/Board.vue
- src/components/BoardList.vue
- src/components/DashboardOptions.vue
- src/components/DashboardSubOptions.vue
- src/components/PastDashboard.vue
- src/components/PresentDashboard.vue
- src/components/WIPList.vue
- src/components/WIPLists.vue
- src/store/mutations.js
- src/store/store.js
Es una pr antigua que tenía Jose Luis, con los últimos cambios que tenía.
> New dashboard
